# Site settings
title: Sticky Sidebar jQuery
tag_text: Sticky Sidebar
description: 

# Build settings
markdown: kramdown
exclude: ["README.md", "node_modules"]
sass:
  style: compressed
repository: abouolia/sticky-sidebar.git